require 'open-uri'
require 'nokogiri'
require 'json'

class CSS3Fetcher
  def url
    'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference'
  end

  def doc
    Nokogiri::HTML(html)
  end

  def html
    open(url).read
  end

  def fetch
    codes          = doc.search('#wikiArticle .index code')
    all_properties = codes.map{|x| x.text }
    css3 = all_properties.select do |x|
      ( not x.include?('()') ) and
      ( not x.include?(':')  ) and
      ( not x.include?('@')  ) and
      ( not x.include?('>')  )
    end
  end
end

class CSS2Fetcher
  def url
    'http://xhtml.com/en/css/reference/'
  end

  def doc
    Nokogiri::HTML(html)
  end

  def html
    open(url).read
  end

  def fetch
    doc.search('dl a').map{|x| x.text }
  end
end

properties = (CSS3Fetcher.new.fetch + CSS2Fetcher.new.fetch).sort.uniq


template = <<TEMPLATE
// GENERATED by sh/fetch_css_properties.rb
Csster.allProperties = #{JSON.pretty_generate(properties)}
TEMPLATE

File.open('src/properties.js', 'w') do |f|
  f.puts template
end
