require 'open-uri'
require 'nokogiri'
require 'json'


module Fetcher
  def doc
    @doc ||= Nokogiri::HTML(html)
  end

  def html
    puts "fetching #{url}"
    open(url).read
  end
end

#TODO http://help.dottoro.com/lccxfjst.php (may also include from here)
class CSS3Fetcher
  include Fetcher
  def url
    'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference'
  end

  def fetch
    codes          = doc.search('#wikiArticle .index code')
    all_properties = codes.map{|x| x.text }
    css3 = all_properties.select do |x|
      ( not x.include?('()') ) and
      ( not x.include?(':')  ) and
      ( not x.include?('@')  ) and
      ( not x.include?('>')  )
    end
  end
end

class CSS2Fetcher
  include Fetcher
  def url
    'http://xhtml.com/en/css/reference/'
  end

  def fetch
    doc.search('dl a').map{|x| x.text }
  end
end

class SVGFetcher
  include Fetcher
  def url
    'https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute'
  end

  def fetch
    # first p sibling has all SVG attrs, that can be used in CSS
    doc.search('#Presentation_attributes ~ p')[0].search('code').map{|x| x.text }
  end
end

properties = (CSS3Fetcher.new.fetch + CSS2Fetcher.new.fetch + SVGFetcher.new.fetch).sort.uniq
# some props are still not accepted as standard (eg. zoom), add it manually
(properties += ['zoom']).sort!.uniq!

template = <<TEMPLATE
// GENERATED by sh/fetch_css_properties.rb
Csster.allProperties = #{JSON.pretty_generate(properties)}
TEMPLATE

File.open('src/properties.js', 'w') do |f|
  f.puts template
end
